doc: remove obsolete mention of dropbear
xenserver/host-installer pull request #30
Opened 2023-01-02 14:27 UTC by ydirson

2023-01-23 09:50 UTC, rosslagerwall submitted a review, later dismissed

2023-01-23 20:34 UTC, andyhhp requested changes

2023-01-23 20:34 UTC, andyhhp commented on doc/parameters.txt
> +    Start a ssh server with the root password set as requested.
"Start an ssh server"

2023-01-24 10:13 UTC, andyhhp approved these changes

2023-01-25 18:33 UTC, rosslagerwall approved these changes

2023-01-25 18:33 UTC, merged